### ISSUE TITLE
mzw你给我出来

### ISSUE THREAD

**Issue by dabao1955** [mzwing/blog#1]
![Screenshot_2023-07-25-12-07-57-60_df198e732186825c8df26e3c5a10d7cd](https://github.com/mzwing/blog/assets/79307765/19d08609-8f39-4938-aabd-644192e4dfee)
你给我解释一下(

**Comment by mzwing** [comment]
有什么好解释的（）

**Comment by dabao1955** [comment]
> 有什么好解释的（）

你大爷，

**Comment by mzwing** [comment]
（）

**Comment by dabao1955** [comment]
> （）

mzw:Segmentation fault (core dumped)

~~为什么outlook要给我发两封邮件，我差点以为我pr被合并了(~~

**Comment by mzwing** [comment]
乐乐

mzw：soga（无关心）

**Comment by chihuo2104** [comment]
乐

**Comment by mzwing** [comment]
> ~~为什么outlook要给我发两封邮件，我差点以为我pr被合并了(~~

因为我除了回复你之外我还顺便把这个issue关掉了啊（）

**Comment by mzwing** [comment]
> 乐

chi：\*乐乐乐\*
